-- MySQL Script generated by MySQL Workbench
-- Tue Mar 29 16:50:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_orders
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_orders
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_orders` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `food_orders` ;

-- -----------------------------------------------------
-- Table `food_orders`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `level_id` INT NOT NULL,
  `status` TINYINT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_user_level1_idx` (`level_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `food_orders`.`levels` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`merchants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`merchants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `corporate_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '1',
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_merchant_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_merchant_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_orders`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL DEFAULT '1',
  `name` VARCHAR(45) NOT NULL,
  `descripion` VARCHAR(100) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `category_id` INT NOT NULL,
  `merchant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catalog_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_catalog_merchant1_idx` (`merchant_id` ASC) VISIBLE,
  CONSTRAINT `fk_catalog_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_orders`.`category` (`id`),
  CONSTRAINT `fk_catalog_merchant1`
    FOREIGN KEY (`merchant_id`)
    REFERENCES `food_orders`.`merchants` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`additional_permited`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`additional_permited` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `item_group_id` INT NOT NULL,
  `catalog_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_additional_item_group1_idx` (`item_group_id` ASC) VISIBLE,
  INDEX `fk_additional_catalog1_idx` (`catalog_id` ASC) VISIBLE,
  CONSTRAINT `fk_additional_catalog1`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `food_orders`.`product` (`id`),
  CONSTRAINT `fk_additional_item_group1`
    FOREIGN KEY (`item_group_id`)
    REFERENCES `food_orders`.`item` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `catalog_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_orders_catalog1_idx` (`catalog_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_catalog1`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `food_orders`.`product` (`id`),
  CONSTRAINT `fk_orders_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `food_orders`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`orders_additional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`orders_additional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `orders_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_additional_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_orders_additional_item1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_additional_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `food_orders`.`item` (`id`),
  CONSTRAINT `fk_orders_additional_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `food_orders`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `food_orders`.`status_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_orders`.`status_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `users_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_status_orders_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_status_orders_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_status_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `food_orders`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status_orders_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `food_orders`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
